---
title: null
class_no: null
class_date: null
qrimage: null
qrbottom: '-20%'
pageurl: null
framework: revealjs
highlighter: highlight.js
hitheme: zenburn
widgets:
  - mathjax
url:
  lib: ../../libraries
  assets: ../../assets
mode: selfcontained
knit: 'slidify::knit2slides'
revealjs:
  theme: solarized_jg
  center: false
  controls: false
mathjax:
  sans-serif: true
---

`{r setup, cache = F, echo = F} knitr::knit_hooks$set(document = function(doc){   gsub('`` ', '`', doc)<br>})

````
```{r utility_functions, cache = F, echo = F, eval = T, message=FALSE}
knitr::opts_chunk$set(cache=FALSE,fig.height=10,fig.width=17.7,dpi=108)

find_semester_dir <- function(p = NULL) {
  if (is.null(p)) p <- getwd()
  p <- normalizePath(p)
  if (file.exists(file.path(p,'semester.yml'))) {
    return(p)
  } else {
    d <- dirname(p)
    if (d == p) return(NA)
    return(find_semester_dir(d))
  }
}

semester.dir <- find_semester_dir()
data.dir <- file.path(semester.dir, 'data')
script.dir <- file.path(semester.dir,'util_scripts')

source_semester_script <- function(script) {
  script_file <- file.path(script.dir, script)
  message("Running script", script_file)
  source(script_file, chdir = T)
}

eval_in_sem_script_dir <- function(expr, loc = script.dir) {
  this.dir <- getwd()
  setwd(loc)
  retval <- eval(expr)
  setwd(this.dir)
  invisible(retval)
}

library(ggplot2)
library(magrittr)
library(stringr)
library(dplyr)
library(tidyr)

source_semester_script('lecture_utils.R')
````

This is a template for creating a quick lecture for a course using Slidify.<br>To initialize the directory and file structure for a lecture, run

```
source('build_lectures.R')
author_lecture(lecture_number)
```

Once you have your `index.Rmd` source file,<br>all you need to do is to run `build_lectures()` from the root directory for the semester<br>or run `build_lecture()` from the lecture directory.

--------------------------------------------------------------------------------

# Math examples
$x = \sqrt{\left[\frac{\sin(\theta)}{\ln(\psi)}\right]}$

[<br>x = \sqrt{\left[\frac{\sin(\theta)}{\ln(\psi)}\right]}<br>]
