[Settings]
  ID = "ees3310"

[[redirects]]
  from = "/static/*"
  to = "https://static.jgilligan.org/ees3310/:splat"
  status = 200

[[redirects]]
  from = "/climatemodels/*"
  to = "http://climatemodels.uchicago.edu/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
