---
title: Goals of Climate Policy
class_date: '2018-10-26'
class_number: 28
weight: 28
slug: reading_28
pubdate: '2018-08-20'
date: '2018-10-26'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
## Reading:

* Climate Casino, Ch. 17.
* The Climate Fix, Ch. 6.

### Reading Notes:

* In these chapters, Pielke and Nordhaus offer different accounts of the history of international treaties and policies to manage climate change.
* Much of the focus is on the United Nations Framework Convention on Climate Change (UNFCCC), signed in 1992 and ratified by all 193 member states of the United Nations.
* The UNFCCC is legally binding on its signatories, and requires them to " stabiliz[e] greenhouse gases concentrations in the atmosphere at a level that would avoid dangerous anthropogenic interference with the climate system." A problem is that the Framework did not define what constituted "dangerous anthropogenic interference," or spell out any specific actions that the signatories would have to take under the treaty.
* In subsequent years, much of the world's scientific and climate policy elites arrived at a rough consensus that raising the average temperature of the earth by more than \SI{2}{\celsius} relative to preindustrial temperatures would constitute dangerous interference. Both Nordhaus and Pielke present critical examinations of this judgment.
* The details of implementing the pledge under UNFCCC (both defining 'dangerous interference" and deciding on specific actions) was left to subsequent negotiations, and the signatory nations have met every year at "conferences of parties" (COPs) to hammer out details. The most important implementation agreement was a treaty signed in Kyoto in 1998, but never ratified by the United States. Both Nordhaus and Pielke discuss the Kyoto treaty and its pros and cons.
* As you read this history and the discussion of the goal of limiting warming to no more than \SI{2}{\celsius} above pre-industrial temperatures, try to become familiar with the history and think critically about the kinds of policies that were pursued and those that were not given serious consideration.
