---
title: The Cost of Reducing Emissions
class_date: '2018-10-24'
class_number: 27
weight: 27
slug: reading_27
pubdate: '2018-07-31'
date: '2018-10-24'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
## Reading:

### Required Reading (everyone):
* Climate Casino, Ch. 14, pp. 157--165.
* Climate Casino, Ch. 15.

### Reading Notes:

Here, we focus on the cost of reducing emissions. You should skim the material from Ch. 14 lightly and focus on reading Ch. 15 carefully.
Remember how, in the reading notes for Oct. 9, I warned you about the potential confusion between "mitigating factors," (the benefits of global warming, such as reduced heating costs for people who live in cold climates and longer growing seasons for farmers, which can offset some of the harms) and "mitigation," which means cutting greenhouse gas emissions. Here, we are talking about the latter.

* Nordhaus distinguishes two kinds of economic analysis of the cost of mitigation: Top-down and bottom-up (pp. 174--76 and Fig. 25). What is the difference? Do you think one is more reliable than the other? Why or why not?
* Nordhaus discusses two aspects of mitigating greenhouse gas emissions: the technical aspects that determine what a perfect policy that is efficiently implemented could do; and the human aspects, which cause policies to be imperfectly designed and inefficently implemented in the real world. Compare the two curves in Fig. 26.
