---
title: How Will Climate Change Affect Our Lives? (Part 1)
class_date: '2018-10-08'
class_number: 21
weight: 21
slug: reading_21
pubdate: '2018-08-20'
date: '2018-10-08'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
## Reading:

### Required Reading (everyone):
* Climate Casino, 6--9.

### Reading Notes:

This reading assignment covers many pages, but the material is descriptive, not mathematical.
What I am looking for you to get out of this is a sense of the different kinds of impacts that climate change might have on our lives and the lives of people around the planet.

* Pay particular attention to the distinction Nordhaus draws between **managed**, **unmanaged**, and **unmanageable** systems.
* Also pay attention to the discussions of **adaptation** and **mitigation**.

    1.[Mitigating factors] mean aspects of climate change that may be beneficial and mitigate the damage caused by the harmful aspects.
    This can be confusing because in the context of climate policy **mitigation** usually means reducing the amount of climate change
    (e.g., by reducing greenhouse gas emissions), whereas
    **mitigating factors** are things that reduce the impact that a given amount of climate change will have on people's lives.
    1.[Adaptation] means changes people make in the way they live and the kinds of economic activities they pursue in order to adapt to living in a different climate.

    Adaptation and mitigating factors are important because they show us that there can be more to climate change policy than just reducing greenhouse gas emissions.
    Again, to point out how confusing this terminology can be, _mitigating factors_ (things that reduce the impact of climate change on people's lives) show that there is more to climate policy than _mitigation_ (reducing greenhouse gas emissions).
* In the three chapters on details (7--9), try to get a feel for the following questions:

    1. How severe are the threats likely to be to human well-being?
    1. Are certain groups of people especially vulnerable?
    1. What kinds of mitigating factors might reduce the impact of climate change?
    1. What kinds of adaptations might make it easier to live with climate change?

* In the chapter on farming, pay attention to the discussion of productivity growth in the worlds' economies (basically this is the growth of $g$, the per-capita GDP, in the Kaya identity, which we read about on p. 30 of Ch. 3, and which we'll study in greater detail when we look at decarbonizing the world's energy supply on Oct. 15--22.). How does growing productivity affect the way we look at climate change?
* In the chapter on farming, why is figure 15 important to the discussion of adaptation and mitigation?
* In the chapter on health impacts, don't try to get every detail but do try to get a sense of what the biggest climate related threats to health are likely to be and what kinds of adaptive things people could do to fight them as temperatures rise.
* In the chapter on the oceans, there are two distinct threats: sea-level rise and ocean acidification. Get a feel for how each affects people's lives and what adaptations might be possible.
