---
title: 'The Carbon Cycle: Ocean and Biosphere'
class_date: '2018-09-12'
class_number: 10
weight: 10
slug: reading_10
pubdate: '2018-08-20'
date: '2018-09-12'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
## Reading:

* Understanding the Forecast, Ch. 8, pp. 89--97.

### Reading Notes:

* Know the different forms carbon takes in the earth system: CO~2~ and organic gases in the atmosphere; dissolved inorganic carbon in the hydrosphere (carbonic acid and related ions: H~2~CO~3~, HCO~3~^-^, CO~3~^-2^); solid organic and inorganic matter in the lithosphere (what's the difference between organic and inorganic? What are dominant forms that each takes in the lithosphere?); and living organic carbon in the biosphere.
* What are **oxidation** and **reduction** and how do they affect organic and inorganic carbon?
* Focus intently on Fig. 8.1: get a feel for the size of each reservoir and the magnitude of flux between the different reservoirs. Don't feel that you have to memorize the numbers, but you should have a good feel for which are larger, which are smaller, and a general sense of the range of sizes.
* What are the dominant mechanisms by which carbon moves from one reservoir to another? Which processes are fast and which are slow?
* In Fig. 8-2, why are the annual wiggles in the atmospheric carbon concentration so much bigger in Hawaii than in New Zealand?
* How might feedbacks in the carbon cycle destabilize the global climate?
* Try to get a rough feel for the orbital forcing of climate, but don't stress about the details. We'll dig into this in much more depth when we look at climates of the past, on Sep. 19--21. The key here is to understand that small variations in the earth's orbit lead to small forcings on the climate, which are dramatically amplified by a positive feedback in the carbon cycle to produce the cycle of ice ages that the earth experienced over the past 2 million years or so.
