---
title: The Case for Renewable Energy
class_date: '2018-11-09'
class_number: 34
weight: 34
slug: reading_34
pubdate: '2018-07-31'
date: '2018-11-09'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
## Reading:

### Required Reading (everyone):
* Handout: M.Z. Jacobson and M.A. Delucchi, "A Path to Sustainable Energy by 2030," Scientific American, Nov. 2009, pp. 58--65 (posted on Brightspace).
* Handout: E. Porter, "Fisticuffs over the Route to a Clean-Energy Future," New York Times June 20, 2017, p. B1 (posted on Brightspace).
* Handout: C. Mooney, "A Bitter Scientific Debate just Erupted over the Future of America's Power Grid," Washington Post June 19, 2017 (posted on Brightspace).

### Required for Grad Students (optional for undergrads):
* Handout: M.Z. Jacobson _et al_., "Low-cost solution to the grid reliability problem with 100% penetration of intermittent wind, water, and solar for all purposes," PNAS **112**, 15060 (2015) (posted on Brightspace).
* Handout: C.T.M. Clack _et al_., "Evaluation of a Proposal for Reliable Low-Cost Grid Power with 100% Wind, Water, and Solar," PNAS **114**, 6722 (2017) (posted on Brightspace).
* Handout: M.Z. Jacobson _et al_., "The United States Can Keep the Grid Stable at Low Cost with 100% Clean, Renewable Energy in All Sectors, Despite Inaccurate Claims," PNAS **114*, E5021 (2017) (posted on Brightspace).

### Reading Notes:

Pielke has argued that we don't have the technology necessary to abandon fossil fuels. Jacobson and Delucchi disagree and present a proposal here.

* "A path to sustainable energy" presents Jacobson and Delucchi's proposal to the general public. "Low-cost solution to the grid reliabilty problem" (optional for undergrads) provides up-to-date technical details for implementing this plan in the US.
* "Evaluation of a proposal" (optional for undergraduates) is a fierce critique by a group of scientists and engineers. Jacobson _et al._ reply to this critique in "The United States can keep the grid stable." This exchange spawned a huge fight in the clean energy research community with accusations of dishonesty on all sides. The news stories "Fisticuffs" and "A bitter scientific debate" describe this fight.
* As you read Jacobson and Delucchi's proposal and its critics, think about both the technical and political aspects:

    * Are Jacobson and his co-authors persuasive when they argue that we have the technology that we need to quickly transition from fossil fuels to renewable energy?
    * If we do have the technology, what political obstacles would you see to implementing this proposal?
