---
title: The Case for Nuclear Energy
class_date: '2018-11-12'
class_number: 35
weight: 35
slug: reading_35
pubdate: '2018-07-31'
date: '2018-11-12'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
## Reading:

### Required Reading (everyone):
* Handout: R.K. Lester, "A Roadmap for U.S. Nuclear Energy Innovation," Issues in Science and Technology **32** (2) (Winter, 2016) (posted on Brightspace).
* Handout: D. Ropeik, "Clean Energy Mind Games," Issues in Science and Technology **33** (4) (Summer, 2017) (posted on Brightspace).
* Handout: C. Tomlinson, "Nuclear Power as We Know it Is Finished," Houston Chronicle Aug. 3, 2017 (posted on Brightspace).

### Reading Notes:

Nuclear power has the potential to provide abundant clean energy with no greenhouse gas emissions. However, there are two separate problems that nuclear power must contend with: First, it is very expensive. Several years ago, the CEO of Excelon, the largest operator of nuclear power plants in the U.S., said that nuclear power was more expensive than any other source of energy except solar photovoltaic. Second, nuclear power is politically controversial because of public fears about safety, especially after the 2011 nuclear accident in Fukushima, Japan.

In these readings, "Nuclear power as we know it is finished" and "A roadmap for U.S. nuclear energy innovation" discuss the economics and the prospects for whether nuclear power can become economically competitive. "Clean energy mind games" is written by an expert on risk and discusses the safety issues and public fears.
