---
title: Introduction to Reproducible Research
lab_date: '2018-08-27'
report_due_date: '2018-09-03'
lab_number: 1
github_classroom_assignment_url: https://classroom.github.com/a/gvdNarpA
pubdate: '2018-07-31'
date: '2018-08-27'
slug: lab_01_assignment
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
This lab will introduce the principles of reproducible research and the tools we will use to perform the tasks of reproducible research.

Before you come to class Monday, please set up a free account on GitHub, as described in "Introduction to Git and GitHub Classroom." After you sign up on GitHub will probably also want to register on GitHub as a student (<https://education.github.com/students>), to get a bunch of free extra features.

## Reading

**Before you come to lab**, please read the following documents:

* [Introduction to EES 3310/5310 Labs](/lab_docs/lab_01_overview)
* [Introduction to Reproducible Research](/lab_docs/lab_01_reproducible_research)
* [Introduction to Git and GitHub Classroom](/lab_docs/lab_01_git_intro)
* [Introduction to R and RMarkdown](/lab_docs/lab_01_rmarkdown_intro)
* [No more excuses for non-reproducible methods (optional)](/lab_docs/lab_01_no_more_excuses)

## Assignment

Accept the assignment at GitHub Classroom at <https://classroom.github.com/a/gvdNarpA>.
